// Generated by CoffeeScript 2.3.0
var indexOf = [].indexOf;

export default (parents, children, initData) => {
  var newTitle, temp;
  newTitle = initData.reduce((r, c) => {
    return [...r, c.title];
  }, []);
  if (indexOf.call(newTitle, parents) >= 0) {
    return initData.reduce((r, c) => {
      return [
        ...r,
        c.title === parents ? {
          title: parents,
          child: c.child.concat(children)
        } : c
      ];
    }, []);
  } else {
    temp = [
      {
        title: parents,
        child: children
      }
    ];
    return initData = [...temp, ...initData];
  }
};
