// Generated by CoffeeScript 2.3.0
/* eslint-disable import/first */
var data, initData;

import func from './demo';

initData = [
  {
    title: 'parent 1',
    child: ['child 1',
  'child 2']
  },
  {
    title: 'parent 2',
    child: ['child 1',
  'child 2']
  }
];

data = func('Welcome', ['hello', 'world'], initData);

export default data;
